# Auto-generated by generate_cffi_defs.py – DO NOT EDIT
CDEF_SOURCE = '''\
typedef struct {
    int node_id;
    int delay_ms;
    float x;
    float y;
    int radius;
} NodeData;
typedef struct {
    int from_id;
    int to_id;
} EdgeData;
typedef struct {
    int nb_ants;
    int set_nb_nodes;
    int min_hops;
    int max_hops;
    int default_min_delay;
    int default_max_delay;
    int death_delay;
    int under_attack_id;
    _Bool attack_started;
    _Bool simulate_ddos;
    _Bool show_random_performance;
    _Bool show_brute_performance;
    double ranking_alpha;
    double ranking_beta;
    double ranking_gamma;
    float ant_alpha;
    float ant_beta;
    float ant_Q;
    float ant_evaporation;
} AppConfig;
typedef struct {
    int candidate_nodes[1024];
    int candidate_count;
    int current_L;
    int permutation[1024];
    int combination[1024];
    int at_first_permutation;
    int at_first_combination;
    int done;
} BruteForceState;
typedef struct {
    int *nodes;
    int node_count;
    int total_latency;
} AntNetPathInfo;
typedef struct {
    char __size[56];
} pthread_attr_t;
typedef struct {
    char __size[40];
} pthread_mutex_t;
typedef struct {
    char __size[4];
} pthread_mutexattr_t;
typedef struct {
    char __size[48];
} pthread_cond_t;
typedef struct {
    char __size[4];
} pthread_condattr_t;
typedef struct {
    char __size[56];
} pthread_rwlock_t;
typedef struct {
    char __size[8];
} pthread_rwlockattr_t;
typedef struct {
    char __size[32];
} pthread_barrier_t;
typedef struct {
    char __size[4];
} pthread_barrierattr_t;
typedef struct {
    int *adjacency;
    int adjacency_size;
    float *pheromones;
    int pheromone_size;
    float alpha;
    float beta;
    float evaporation;
    float Q;
    int num_ants;
    int is_initialized;
} AcoV1State;
typedef struct HeatmapRenderer HeatmapRenderer;
typedef struct {
    double best_L;
    int last_improve_iter;
    int m;
    double sum_tau;
    double sum_r;
    double score;
} SasaState;
typedef struct {
    char name[8];
    double score;
    int latency_ms;
} RankingEntry;
typedef struct {
    double alpha;
    double beta;
    double gamma;
} SasaCoeffs;
typedef struct {
    int node_count;
    int min_hops;
    int max_hops;
    NodeData *nodes;
    int num_nodes;
    EdgeData *edges;
    int num_edges;
    int iteration;
    pthread_mutex_t lock;
    int random_best_nodes[1024];
    int random_best_length;
    int random_best_latency;
    AppConfig config;
    int brute_best_nodes[1024];
    int brute_best_length;
    int brute_best_latency;
    BruteForceState brute_state;
    int aco_best_nodes[1024];
    int aco_best_length;
    int aco_best_latency;
    AcoV1State aco_v1;
    SasaState aco_sasa;
    SasaState random_sasa;
    SasaState brute_sasa;
    SasaCoeffs sasa_coeffs;
} AntNetContext;
typedef struct {
    pthread_mutex_t lock;
    NodeData *start_node;
    NodeData *end_node;
    NodeData *hop_nodes;
    size_t hop_count;
    EdgeData *edges;
    size_t edge_count;
    int default_min_delay;
    int default_max_delay;
} HopMapManager;



HeatmapRenderer *hr_create(int width, int height);
int hr_render(HeatmapRenderer *hr, const float *pts, const float *strength, size_t n, unsigned char *out_rgba, int width, int height);
void hr_destroy(HeatmapRenderer *hr);
int hr_renderer_start(int width, int height);
int hr_renderer_stop(void);
int hr_enqueue_render(const float *pts_xy, const float *strength, int n, unsigned char *out_rgba, int width, int height);
void init_sasa_state(SasaState *state);
void update_on_improvement(int iter_idx, double new_latency, SasaState *state, double alpha, double beta, double gamma);
void recalc_sasa_score(SasaState *state, int iter_idx, double alpha, double beta, double gamma);
void compute_ranking(const SasaState *states, int count, int *rank_out);
int antnet_initialize(int node_count, int min_hops, int max_hops);
int antnet_run_iteration(int context_id);
int antnet_shutdown(int context_id);
int antnet_get_best_path(int context_id, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
int antnet_run_all_solvers(int context_id, int *out_nodes_aco, int max_size_aco, int *out_len_aco, int *out_latency_aco, int *out_nodes_random, int max_size_random, int *out_len_random, int *out_latency_random, int *out_nodes_brute, int max_size_brute, int *out_len_brute, int *out_latency_brute);
int antnet_init_from_config(const char *config_path);
int antnet_get_config(int context_id, AppConfig *out);
int antnet_get_pheromone_matrix(int context_id, float *out, int max_count);
int antnet_render_heatmap_rgba(const float *pts_xy, const float *strength, int n, unsigned char *out_rgba, int width, int height);
int antnet_renderer_async_init(int initial_width, int initial_height);
int antnet_renderer_async_shutdown(void);
int antnet_get_algo_ranking(int context_id, RankingEntry *out, int max_count);
int antnet_set_sasa_params(int context_id, double alpha, double beta, double gamma);
int antnet_get_sasa_params(int context_id, double *out_alpha, double *out_beta, double *out_gamma);
int antnet_set_aco_params(int context_id, float alpha, float beta, float Q, float evaporation, int num_ants);
int antnet_get_aco_params(int context_id, float *out_alpha, float *out_beta, float *out_Q, float *out_evaporation, int *out_num_ants);
int antnet_render_path_grid(int context_id, const int *node_ids, int node_count, float offset_x, float offset_y, float *out_coords, int max_coords, int *out_count);
int antnet_update_topology(int context_id, const NodeData *nodes, int num_nodes, const EdgeData *edges, int num_edges);
int random_search_path(AntNetContext *ctx, int start_id, int end_id, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
int brute_force_search_step(AntNetContext *ctx, int start_id, int end_id, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
void brute_force_reset_state(AntNetContext *ctx);
int aco_v1_init(AntNetContext *ctx);
int aco_v1_run_iteration(AntNetContext *ctx);
int aco_v1_get_best_path(AntNetContext *ctx, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
int aco_v1_search_path(AntNetContext *ctx, int start_id, int end_id, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
_Bool config_load(AppConfig *cfg, const char *filepath);
_Bool config_save(const AppConfig *cfg, const char *filepath);
void config_set_defaults(AppConfig *cfg);
HopMapManager *hop_map_manager_create();
void hop_map_manager_destroy(HopMapManager *mgr);
void hop_map_manager_set_delay_range(HopMapManager *mgr, int min_delay, int max_delay);
void hop_map_manager_initialize_map(HopMapManager *mgr, int total_nodes);
void hop_map_manager_create_default_edges(HopMapManager *mgr);
void hop_map_manager_export_topology(HopMapManager *mgr, NodeData *out_nodes, size_t *out_node_count, EdgeData *out_edges, size_t *out_edge_count);
void hop_map_manager_recalc_positions(HopMapManager *mgr, float scene_width, float scene_height);
int pr_render_path_grid(const AntNetContext *ctx, const int *node_ids, int node_count, float offset_x, float offset_y, float *out_coords, int max_coords, int *out_count);
'''