#src/python/consts/_generated/error_codes_generated.py
# This file is auto-generated by errors_const_c2python.py
# Do not edit manually.

"""
Python equivalents of C error code constants from error_codes.h.
"""

ERR_SUCCESS = 0
ERR_INVALID_ARGS = -1
ERR_NO_TOPOLOGY = -2
ERR_NO_PATH_FOUND = -3
ERR_ARRAY_TOO_SMALL = -4
ERR_UNIMPLEMENTED = -5
ERR_MEMORY_ALLOCATION = -6
ERR_INVALID_CONTEXT = -7
ERR_NO_FREE_SLOT = -8
